# -*- coding: utf-8 -*-
"""WebGIS_Wisata_Larantuka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h9nkJX_0_uwHedr2ChxoyriBTKkgmYeE

# 🗺️ WebGIS Dashboard Wisata Larantuka

Notebook ini membangun ulang dashboard **WebGIS Wisata Larantuka** (Machine Learning + Peta Interaktif) di **Google Colab**.

**Alur kerja:**
1. Ambil data dari Google Sheet hasil Google Forms
2. Bersihkan & siapkan data
3. **Random Forest** → prediksi *Popularitas* tempat wisata
4. **K-Means** → clustering tempat wisata berdasarkan rating & jumlah review
5. Aturan bisnis → *Potensi Pengembangan*
6. Render **dashboard HTML interaktif** (peta + filter + grafik) persis seperti mockup

> Jalankan cell dari atas ke bawah secara berurutan.
"""

# ==========================================================
# WEBGIS WISATA LARANTUKA
# STEP 1 - IMPORT LIBRARY
# ==========================================================

import warnings
warnings.filterwarnings("ignore")

import json
import numpy as np
import pandas as pd

import folium
from folium import plugins
from folium.plugins import (
    MarkerCluster,
    MiniMap,
    Fullscreen,
    HeatMap
)

from sklearn.cluster import KMeans
from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler
)
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score,
    classification_report
)

from IPython.display import HTML, IFrame, display

"""## Step 2 — Ambil Data dari Google Sheets (Google Forms)

Cara mendapatkan link CSV dari spreadsheet Google Forms kamu:
1. Buka spreadsheet hasil Google Forms
2. **File → Share → Publish to web**
3. Pilih sheet yang sesuai, format **Comma-separated values (.csv)**, lalu klik **Publish**
4. Copy link yang muncul dan tempel ke variabel `SHEET_CSV_URL` di bawah

Kalau link belum diisi / gagal diakses, notebook otomatis memakai 3 baris data contoh yang kamu berikan supaya tetap bisa dites.
"""

# ==========================================================
# STEP 2 - KONEKSI KE DATA (GOOGLE SHEETS DARI GOOGLE FORMS)
# ==========================================================

SHEET_CSV_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vS9Sd0r-gqT9JE2xsLE6jftKyn9UCgHKqMDQU7IFvWXOQh7Pg5CJYp1RTIiJbarn0HZ1jMHYg2Yrspf/pub?output=csv"


try:
    df_raw = pd.read_csv(SHEET_CSV_URL)
    assert len(df_raw) > 0
    print(f"Berhasil memuat data dari Google Sheets: {len(df_raw)} baris")
except Exception as e:
    print(f"Gagal memuat dari Google Sheets ({e})")
    print("Menggunakan data contoh sementara...")
    df_raw = pd.DataFrame({
        "Timestamp": ["7/28/2026 12:35:01", "7/28/2026 12:37:03", "7/28/2026 12:41:08"],
        "koordinat": [
            "-8.343028666791067, 122.97409550805575",
            "-8.34745708171033, 122.97719634915876",
            "-8.347426231361057, 122.97558791934667",
        ],
        "nama": [
            "The Prayer Park on Fatima Hill",
            "Taman Reinha Rosari",
            "HOTEL LESTARI LARANTUKA",
        ],
        "rating": [4.8, 4.5, 4.0],
        "jumlah_rating": [283, 100, 1],
        "kategori": ["Religi", "Religi", "Umum"],
        "gambar": [
            "https://drive.google.com/open?id=1Ajd5v8hP9qC1l__UZHTiQyKoPzhB0LcU",
            "https://drive.google.com/open?id=1tJWRc_4nlkMMKzmgfCBZsJkdeyw18Lf8",
            "https://drive.google.com/open?id=1_Cf1qPnMAY-wO6l9hjYOD5iC8vLTZzd9",
        ],
    })

df_raw.head()

"""## Step 3 — Pembersihan & Transformasi Data"""

# ==========================================================
# STEP 3 - PEMBERSIHAN & TRANSFORMASI DATA
# ==========================================================

df = df_raw.copy()
df.columns = [str(c).strip().lower() for c in df.columns]

df[["lat", "lon"]] = df["koordinat"].str.split(",", expand=True).astype(float)
df["rating"] = pd.to_numeric(df["rating"], errors="coerce")
df["jumlah_rating"] = pd.to_numeric(df["jumlah_rating"], errors="coerce")
df["kategori"] = df["kategori"].astype(str).str.strip().str.title()
df["nama"] = df["nama"].astype(str).str.strip()

df = df.dropna(subset=["lat", "lon", "rating", "jumlah_rating"]).reset_index(drop=True)


def drive_direct_link(url):
    """Ubah link share Google Drive jadi link gambar yang bisa ditampilkan langsung."""
    url = str(url)
    if "drive.google.com" not in url:
        return url
    try:
        file_id = url.split("id=")[-1].split("&")[0]
        return f"https://drive.google.com/thumbnail?id={file_id}&sz=w1000"
    except Exception:
        return url


df["gambar_url"] = df["gambar"].apply(drive_direct_link)

print(f"Total data bersih: {len(df)} tempat wisata")
df.head()

"""## Step 4 — Machine Learning #1: Prediksi Popularitas (Random Forest)

Belum ada label "populer / tidak populer" secara eksplisit di data, jadi label awal (*ground truth*) dibuat dari aturan domain (rating tinggi + jumlah review banyak). **Random Forest** kemudian dilatih mempelajari pola tsb, sehingga ke depannya bisa memprediksi status popularitas tempat wisata baru secara otomatis — bukan sekadar mengulang aturan manual.
"""

# ==========================================================
# STEP 4 - MACHINE LEARNING #1: PREDIKSI POPULARITAS (RANDOM FOREST)
# ==========================================================

def label_popularitas(row):
    if row["rating"] >= 4.3 and row["jumlah_rating"] >= 50:
        return "Sangat Populer"
    return "Populer"

df["label_popularitas"] = df.apply(label_popularitas, axis=1)

le_kategori = LabelEncoder()
df["kategori_enc"] = le_kategori.fit_transform(df["kategori"])

X = df[["rating", "jumlah_rating", "kategori_enc"]]
y = df["label_popularitas"]

if y.nunique() < 2 or len(df) < 8:
    print("Data masih sedikit / label belum bervariasi untuk split train-test.")
    print("Model tetap dilatih pada seluruh data sebagai contoh.")
    rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
    rf_model.fit(X, y)
    df["prediksi_popularitas"] = rf_model.predict(X)
else:
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )
    rf_model = RandomForestClassifier(n_estimators=200, random_state=42)
    rf_model.fit(X_train, y_train)
    y_pred = rf_model.predict(X_test)
    print("Akurasi Random Forest:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    df["prediksi_popularitas"] = rf_model.predict(X)

df[["nama", "rating", "jumlah_rating", "prediksi_popularitas"]]

"""## Step 5 — Machine Learning #2: Clustering K-Means"""

# ==========================================================
# STEP 5 - MACHINE LEARNING #2: CLUSTERING K-MEANS
# ==========================================================

scaler = StandardScaler()
X_cluster = scaler.fit_transform(df[["rating", "jumlah_rating"]])

n_clusters = max(1, min(4, df["nama"].nunique()))
kmeans_model = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
df["cluster"] = kmeans_model.fit_predict(X_cluster)

df[["nama", "rating", "jumlah_rating", "cluster"]]

"""## Step 6 — Aturan Bisnis: Potensi Pengembangan"""

# ==========================================================
# STEP 6 - ATURAN BISNIS: POTENSI PENGEMBANGAN
# ==========================================================

def label_potensi(row):
    if row["rating"] >= 4.5 and row["jumlah_rating"] < 100:
        return "Sangat Potensial"
    if row["rating"] >= 4.5 and row["jumlah_rating"] >= 100:
        return "Dipertahankan"
    if row["rating"] < 4.0:
        return "Direkomendasikan Kunjungan"
    return "Potensial"

df["potensi_pengembangan"] = df.apply(label_potensi, axis=1)
df[["nama", "rating", "jumlah_rating", "potensi_pengembangan"]]

"""## Step 7 — Ringkasan Statistik & Data untuk Dashboard"""

# ==========================================================
# STEP 7 - RINGKASAN STATISTIK & PERSIAPAN DATA
# ==========================================================

total_wisata = len(df)
rata_rating = round(df["rating"].mean(), 2)
total_review = int(df["jumlah_rating"].sum())

try:
    update_terakhir = pd.to_datetime(df["timestamp"]).max().strftime("%d %b %Y  %H:%M")
except Exception:
    update_terakhir = "-"

center_lat = float(df["lat"].mean())
center_lon = float(df["lon"].mean())

places = df[[
    "nama", "lat", "lon", "rating", "jumlah_rating", "kategori", "gambar_url",
    "prediksi_popularitas", "potensi_pengembangan", "cluster"
]].to_dict(orient="records")

for p in places:
    p["rating"] = float(p["rating"])
    p["jumlah_rating"] = int(p["jumlah_rating"])
    p["cluster"] = int(p["cluster"])

data_json = json.dumps(places, ensure_ascii=False)

kategori_counts = df["kategori"].value_counts().to_dict()
kategori_counts_json = json.dumps(kategori_counts, ensure_ascii=False)

top5_rating = (
    df.sort_values("rating", ascending=False)
    .head(5)[["nama", "rating"]]
    .to_dict("records")
)
top5_review = (
    df.sort_values("jumlah_rating", ascending=False)
    .head(5)[["nama", "jumlah_rating"]]
    .to_dict("records")
)

kategori_list = sorted(df["kategori"].unique().tolist())
potensi_list = ["Sangat Potensial", "Potensial", "Dipertahankan", "Direkomendasikan Kunjungan"]

print("Total wisata     :", total_wisata)
print("Rata-rata rating :", rata_rating)
print("Total review     :", total_review)
print("Update terakhir  :", update_terakhir)

"""## Step 8 — Peta Dasar dengan Folium (Engine Peta)"""

# ==========================================================
# STEP 8 - PETA DASAR DENGAN FOLIUM
# ==========================================================

m = folium.Map(
    location=[center_lat, center_lon],
    zoom_start=15,
    tiles="CartoDB positron",
    zoom_control=False,
    control_scale=False,
)

Fullscreen(
    position="topright",
    title="Perbesar layar",
    title_cancel="Keluar layar penuh",
).add_to(m)

# Paksa Folium membangun seluruh struktur HTML
root = m.get_root()
root.render()

map_var_name = m.get_name()

folium_head = root.header.render()
folium_body = root.html.render()
folium_script = root.script.render()

print("Nama variabel JS:", map_var_name)
print(len(folium_head), len(folium_body), len(folium_script))

"""## Step 9 — Template Dashboard (HTML + CSS + JS Interaktif)"""

# ==========================================================
# STEP 9 - TEMPLATE DASHBOARD (HTML + CSS + JS)
# ==========================================================
# Peta & marker dibuat & dikontrol lewat Folium + Leaflet (di STEP 8 & 10),
# sedangkan bagian ini adalah "kerangka" tampilan dashboard: header, sidebar
# filter, kartu statistik, panel legenda, dan grafik ringkasan.

def build_filter_checkboxes(values, group):
    rows = []
    for v in values:
        cid = f"{group}-{v}".lower().replace(' ', '-')
        rows.append(
            f'<label class="filter-item" for="{cid}">'
            f'<input type="checkbox" id="{cid}" value="{v}" checked> {v}'
            f'</label>'
        )
    return "".join(rows)


def build_pie_legend(kategori_counts, total):
    colors = {
        "Religi": "#8e44ad", "Umum": "#3498db", "Alam": "#27ae60",
        "Kuliner": "#e74c3c", "Budaya": "#e67e22",
    }
    rows = []
    for k, v in sorted(kategori_counts.items(), key=lambda x: -x[1]):
        pct = round(100 * v / total, 1)
        color = colors.get(k, "#95a5a6")
        rows.append(
            f'<div class="legend-row">'
            f'<span class="legend-dot" style="background:{color}"></span>'
            f'<span class="legend-label">{k}</span>'
            f'<span class="legend-value">{v} ({pct}%)</span>'
            f'</div>'
        )
    return "".join(rows)


def build_top5_rating(rows):

    html = []

    for r in rows:
        html.append(
            f'''
            <div class="top5-row">
                <span>{r["nama"]}</span>
                <span class="top5-value">&#9733; {r["rating"]:.1f}</span>
            </div>
            '''
        )

    return "".join(html)


def build_top5_review(rows):
    items = []
    for i, r in enumerate(rows, start=1):
        items.append(
            f'<div class="top5-row"><span class="top5-rank">{i}.</span>'
            f'<span class="top5-name">{r["nama"]}</span>'
            f'<span class="top5-value">{r["jumlah_rating"]}</span></div>'
        )
    return "".join(items)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Dashboard Wisata Kelurahan Larantuka</title>
__FOLIUM_HEAD__
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet.heat/0.2.0/leaflet-heat.js"></script>
<style>
:root{
  --blue:#2563eb; --blue-light:#eaf1ff;
  --green:#22c55e; --green-light:#e7f9ee;
  --red:#ef4444; --red-light:#fdecec;
  --orange:#f59e0b; --orange-light:#fef3dc;
  --purple:#8e44ad; --purple-light:#f2e9f7;
  --ink:#1f2937; --muted:#6b7280; --line:#e5e7eb; --bg:#f2f4f7;
}
*{box-sizing:border-box}
html,body{margin:0;padding:0;height:100%;background:var(--bg);
  font-family:-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);}
.app{display:grid;height:100vh;
  grid-template-columns:340px 1fr 300px;
  grid-template-rows:auto 1fr auto;
  grid-template-areas:"header header header" "sidebar main legend" "footer footer footer";}

.app-header{grid-area:header;background:#fff;border-bottom:1px solid var(--line);
  padding:14px 22px;display:flex;flex-direction:column;gap:2px;}
.app-header h1{margin:0;font-size:19px;display:flex;align-items:center;gap:8px;}
.app-header p{margin:0;font-size:12.5px;color:var(--muted);}

.sidebar-left{grid-area:sidebar;background:#fff;border-right:1px solid var(--line);
  overflow-y:auto;padding:16px;}
.stat-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-bottom:18px;}
.stat-card{border:1px solid var(--line);border-radius:10px;padding:10px 12px;}
.stat-card .label{font-size:11.5px;color:var(--muted);display:flex;align-items:center;gap:5px;}
.stat-card .value{font-size:19px;font-weight:700;margin-top:4px;}

.section-title{font-size:13px;font-weight:700;margin:14px 0 2px;}
.section-sub{font-size:11px;color:var(--muted);margin-bottom:8px;}
.filter-group{border:1px solid var(--line);border-radius:10px;padding:8px 12px;margin-bottom:10px;}
.filter-item{display:flex;align-items:center;gap:8px;font-size:13px;padding:4px 0;cursor:pointer;}
.filter-item input{accent-color:var(--blue);width:15px;height:15px;}
.filter-item.master{font-weight:600;border-bottom:1px solid var(--line);margin-bottom:4px;padding-bottom:6px;}
.hint-box{background:var(--blue-light);border-radius:10px;padding:10px 12px;font-size:12px;color:#1d4ed8;margin-top:8px;}

.main-content{grid-area:main;display:flex;flex-direction:column;min-width:0;}
.map-wrap{position:relative;flex:1;min-height:320px;border-bottom:1px solid var(--line);}
.map-wrap .folium-map{width:100%!important;height:100%!important;}

.search-box{position:absolute;top:14px;left:14px;right:14px;max-width:420px;z-index:500;}
#search-input{width:100%;padding:10px 14px;border-radius:10px;border:1px solid var(--line);
  box-shadow:0 2px 8px rgba(0,0,0,.08);font-size:13.5px;outline:none;}
#search-results{background:#fff;border-radius:10px;margin-top:4px;box-shadow:0 4px 14px rgba(0,0,0,.12);
  display:none;max-height:220px;overflow-y:auto;}
.search-item{padding:9px 14px;font-size:13px;cursor:pointer;border-bottom:1px solid var(--line);}
.search-item:last-child{border-bottom:none;}
.search-item:hover{background:var(--bg);}

.map-controls-left{position:absolute;top:70px;left:14px;z-index:500;display:flex;flex-direction:column;
  background:#fff;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,.1);overflow:hidden;}
.map-controls-left button{width:34px;height:34px;border:none;background:#fff;border-bottom:1px solid var(--line);
  font-size:17px;cursor:pointer;color:#374151;}
.map-controls-left button:last-child{border-bottom:none;}
.map-controls-left button:hover{background:var(--bg);}

.layer-box{position:absolute;top:62px;right:14px;z-index:500;background:#fff;border-radius:10px;
  box-shadow:0 2px 10px rgba(0,0,0,.1);padding:10px 14px;font-size:13px;min-width:150px;}
.layer-box .title{font-weight:700;font-size:13px;margin-bottom:6px;}
.layer-box label{display:flex;align-items:center;gap:7px;padding:3px 0;cursor:pointer;}
.layer-box input{accent-color:var(--blue);}

.info-card{position:absolute;top:14px;left:50%;transform:translateX(-50%);width:340px;max-width:88%;
  background:#fff;border-radius:14px;box-shadow:0 8px 26px rgba(0,0,0,.18);padding:16px;z-index:600;display:none;}
.info-card .close-btn{position:absolute;top:10px;right:12px;border:none;background:none;font-size:18px;
  cursor:pointer;color:var(--muted);}
.info-card h2{margin:0 18px 6px 0;font-size:16px;color:var(--purple);}
.info-card .stars{color:#f59e0b;letter-spacing:1px;font-size:15px;}
.info-card .rating-row{display:flex;align-items:center;gap:6px;font-size:13px;margin-bottom:8px;}
.info-card .rating-num{font-weight:700;}
.kat-badge{display:inline-block;padding:2px 10px;border-radius:20px;font-size:11.5px;color:#fff;
  background:var(--purple);margin-bottom:8px;}
.field-row{font-size:12.5px;color:var(--muted);margin:8px 0 2px;}
.field-value{margin-bottom:4px;}
.pill{display:inline-block;padding:3px 10px;border-radius:20px;font-size:12px;font-weight:600;}
.info-card .coord{font-size:12px;color:var(--muted);margin-top:6px;}
.info-card img{width:100%;border-radius:10px;margin-top:10px;max-height:170px;object-fit:cover;background:#eee;}
.info-card .gmaps{display:inline-flex;align-items:center;gap:5px;font-size:12.5px;color:var(--blue);
  text-decoration:none;margin-top:8px;}

.charts-row{display:grid;grid-template-columns:1fr 1fr 1fr;gap:14px;padding:14px;background:#fff;
  border-top:1px solid var(--line);}
.chart-card{border:1px solid var(--line);border-radius:12px;padding:12px 14px;min-height:210px;}
.chart-card h3{margin:0 0 8px;font-size:13px;}
.pie-card{display:flex;flex-direction:column;}
.pie-inner{display:flex;align-items:center;gap:14px;flex:1;}
.pie-inner canvas{max-width:120px;max-height:120px;}
.legend-list{flex:1;font-size:12px;}
.legend-row{display:flex;align-items:center;gap:6px;padding:3px 0;}
.legend-dot{width:9px;height:9px;border-radius:50%;display:inline-block;}
.legend-label{flex:1;}
.legend-value{color:var(--muted);}
.top5-row{display:flex;align-items:center;gap:8px;font-size:12.5px;padding:5px 0;border-bottom:1px dashed var(--line);}
.top5-row:last-child{border-bottom:none;}
.top5-rank{color:var(--muted);width:16px;}
.top5-name{flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}
.top5-value{font-weight:700;color:#b45309;white-space:nowrap;}

.sidebar-right{grid-area:legend;background:#fff;border-left:1px solid var(--line);
  overflow-y:auto;padding:16px;}
.legend-block{margin-bottom:16px;}
.legend-block h4{margin:0 0 8px;font-size:13.5px;}
.legend-entry{display:flex;gap:9px;margin-bottom:8px;}
.legend-swatch{width:11px;height:11px;border-radius:50%;margin-top:4px;flex-shrink:0;}
.legend-entry .t{font-size:12.5px;font-weight:600;}
.legend-entry .d{font-size:11px;color:var(--muted);}

.app-footer{grid-area:footer;background:#fff;border-top:1px solid var(--line);
  text-align:center;font-size:11.5px;color:var(--muted);padding:9px;}

@media (max-width:980px){
  .app{grid-template-columns:1fr;grid-template-rows:auto auto auto auto auto;
    grid-template-areas:"header" "sidebar" "main" "legend" "footer";height:auto;}
  .map-wrap{height:70vh;}
  .charts-row{grid-template-columns:1fr;}
}
</style>
</head>
<body>
<div class="app">

  <header class="app-header">
    <h1>&#128205; Dashboard Wisata Kelurahan Larantuka</h1>
    <p>Analisis Machine Learning &amp; Potensi Pengembangan</p>
  </header>

  <aside class="sidebar-left">
    <div class="stat-grid">
      <div class="stat-card"><div class="label">&#128205; Total Wisata</div><div class="value">__TOTAL_WISATA__</div></div>
      <div class="stat-card"><div class="label">&#11088; Rata-rata Rating</div><div class="value">__RATA_RATING__</div></div>
      <div class="stat-card"><div class="label">&#128172; Total Review</div><div class="value">__TOTAL_REVIEW__</div></div>
      <div class="stat-card"><div class="label">&#128197; Update Terakhir</div><div class="value" style="font-size:13px;">__UPDATE_TERAKHIR__</div></div>
    </div>

    <div class="section-title">Filter Kategori</div>
    <div class="section-sub">Pilih kategori untuk ditampilkan</div>
    <div class="filter-group" id="filter-kategori">
      <label class="filter-item master" for="kategori-all"><input type="checkbox" id="kategori-all" checked> Pilih Semua</label>
      __FILTER_KATEGORI_HTML__
    </div>

    <div class="section-title">Filter Prediksi Popularitas (Machine Learning)</div>
    <div class="section-sub">Pilih status popularitas</div>
    <div class="filter-group" id="filter-popularitas">
      <label class="filter-item master" for="popularitas-all"><input type="checkbox" id="popularitas-all" checked> Pilih Semua</label>
      <label class="filter-item" for="popularitas-populer"><input type="checkbox" id="popularitas-populer" value="Sangat Populer" checked> Sangat Populer</label>
      <label class="filter-item" for="popularitas-kurang-populer"><input type="checkbox" id="popularitas-kurang-populer" value="Populer" checked> Populer</label>
    </div>

    <div class="section-title">Filter Potensi Pengembangan</div>
    <div class="section-sub">Pilih potensi pengembangan</div>
    <div class="filter-group" id="filter-potensi">
      <label class="filter-item master" for="potensi-all"><input type="checkbox" id="potensi-all" checked> Pilih Semua</label>
      __FILTER_POTENSI_HTML__
    </div>

    <div class="hint-box">&#8505;&#65039; Klik marker pada peta untuk melihat detail analisis setiap tempat wisata</div>
  </aside>

  <main class="main-content">
    <div class="map-wrap">
      __FOLIUM_BODY__

      <div class="search-box">
        <input type="text" id="search-input" placeholder="Cari nama tempat wisata...">
        <div id="search-results"></div>
      </div>

      <div class="map-controls-left">
        <button id="zoom-in" title="Perbesar">+</button>
        <button id="zoom-out" title="Perkecil">&#8722;</button>
        <button id="zoom-reset" title="Kembali ke tengah">&#9678;</button>
      </div>

      <div class="layer-box">
        <div class="title">Pilih Layer</div>
        <label><input type="radio" name="layer-mode" value="normal" checked> Peta Dasar</label>
        <label><input type="radio" name="layer-mode" value="cluster"> Cluster K-Means</label>
        <label><input type="radio" name="layer-mode" value="heat"> Heatmap Kepadatan</label>
      </div>

      <div class="info-card" id="info-card">
        <button class="close-btn" id="info-card-close">&#10005;</button>
        <h2 id="ic-nama"></h2>
        <div class="rating-row">
          <span class="stars" id="ic-stars"></span>
          <span class="rating-num" id="ic-rating"></span>
          <span id="ic-review" style="color:var(--muted)"></span>
        </div>
        <div class="field-row">Kategori</div>
        <div><span class="kat-badge" id="ic-kategori"></span></div>

        <div class="field-row">Prediksi Popularitas (Machine Learning)</div>
        <div class="field-value"><span class="pill" id="ic-popularitas"></span></div>

        <div class="field-row">Potensi Pengembangan</div>
        <div class="field-value"><span class="pill" id="ic-potensi"></span></div>

        <div class="field-row">Cluster K-Means</div>
        <div class="field-value"><span class="pill" id="ic-cluster" style="background:var(--purple-light);color:var(--purple)"></span></div>

        <div class="coord">Koordinat: <span id="ic-koordinat"></span></div>
        <img id="ic-img" src="" alt="foto tempat wisata">
        <div><a class="gmaps" id="ic-gmaps" href="#" target="_blank">&#128205; Buka di Google Maps</a></div>
      </div>
    </div>

    <div class="charts-row">
      <div class="chart-card pie-card">
        <h3>Jumlah Wisata per Kategori</h3>
        <div class="pie-inner">
          <canvas id="pie-chart"></canvas>
          <div class="legend-list">__PIE_LEGEND_HTML__</div>
        </div>
      </div>
      <div class="chart-card">
        <h3>Top 5 Rating Tertinggi</h3>
        __TOP5_RATING_HTML__
      </div>
      <div class="chart-card">
        <h3>Top 5 Review Terbanyak</h3>
        __TOP5_REVIEW_HTML__
      </div>
    </div>
  </main>

  <aside class="sidebar-right">
    <div class="legend-block">
      <h4>Legenda</h4>
    </div>
    <div class="legend-block">
      <h4>Prediksi Popularitas (Machine Learning)</h4>
      <div class="legend-entry"><span class="legend-swatch" style="background:#22c55e"></span>
        <div><div class="t">Sangat Populer</div><div class="d">Potensi dikunjungi banyak orang</div></div></div>
      <div class="legend-entry"><span class="legend-swatch" style="background:#ef4444"></span>
        <div><div class="t">Populer</div><div class="d">Potensi dikunjungi sedikit orang</div></div></div>
    </div>
    <div class="legend-block">
      <h4>Potensi Pengembangan</h4>
      <div class="legend-entry"><span class="legend-swatch" style="background:#22c55e"></span>
        <div><div class="t">Sangat Potensial</div><div class="d">Rating tinggi, review masih rendah</div></div></div>
      <div class="legend-entry"><span class="legend-swatch" style="background:#f59e0b"></span>
        <div><div class="t">Potensial</div><div class="d">Masih bagus untuk dikembangkan</div></div></div>
      <div class="legend-entry"><span class="legend-swatch" style="background:#3b82f6"></span>
        <div><div class="t">Dipertahankan</div><div class="d">Sudah populer, kualitas terjaga</div></div></div>
      <div class="legend-entry"><span class="legend-swatch" style="background:#ef4444"></span>
        <div><div class="t">Direkomendasikan Kunjungan</div><div class="d">Hidden Gem</div></div></div>
    </div>
    <div class="legend-block">
      <h4>Cluster K-Means</h4>
      <div class="legend-entry"><span class="legend-swatch" style="background:#9b59b6"></span>
        <div><div class="t">Review</div><div class="d">Ukuran marker = jumlah review</div></div></div>
    </div>
  </aside>

  <footer class="app-footer">Sumber Data: Google Forms (Real-time) &nbsp;|&nbsp; Analisis: Machine Learning (Random Forest) &amp; K-Means Clustering</footer>
</div>

<script>
__FOLIUM_SCRIPT__
__CUSTOM_JS__
</script>
</body>
</html>
"""

CUSTOM_JS_TEMPLATE = """
(function(){
  var placesData = __DATA_JSON__;
  var mapObj = window["__MAP_VAR__"];

  var potensiColor = {
    "Sangat Potensial": "#22c55e",
    "Potensial": "#f59e0b",
    "Dipertahankan": "#3b82f6",
    "Direkomendasikan Kunjungan": "#ef4444"
  };
  var potensiBg = {
    "Sangat Potensial": ["#e7f9ee", "#15803d"],
    "Potensial": ["#fef3dc", "#b45309"],
    "Dipertahankan": ["#eaf1ff", "#1d4ed8"],
    "Direkomendasikan Kunjungan": ["#fdecec", "#b91c1c"]
  };
  var popBg = {
    "Sangat Populer": ["#e7f9ee", "#15803d"],
    "Populer": ["#fdecec", "#b91c1c"]
  };
  var kategoriColor = {
    "Religi": "#8e44ad", "Alam": "#27ae60", "Kuliner": "#e74c3c",
    "Budaya": "#e67e22", "Umum": "#3498db"
  };
  var clusterPalette = ["#9b59b6", "#16a085", "#e67e22", "#2c3e50", "#f1c40f", "#c0392b"];

  var markerLayer = L.layerGroup().addTo(mapObj);
  var heatLayer = null;
  var selectedPin = null;
  var currentMode = "normal";

  var maxReview = Math.max.apply(null, placesData.map(function(p){ return p.jumlah_rating; })) || 1;

  var state = {
    kategori: new Set(placesData.map(function(p){ return p.kategori; })),
    popularitas: new Set(["Sangat Populer", "Populer"]),
    potensi: new Set(["Sangat Potensial", "Potensial", "Dipertahankan", "Direkomendasikan Kunjungan"]),
    search: ""
  };

  function radiusFromReview(n){
    var minR = 6, maxR = 22;
    var r = minR + (maxR - minR) * Math.sqrt(n / maxReview);
    return Math.max(minR, Math.min(maxR, r));
  }

  function colorFor(place){
    if (currentMode === "cluster") {
      return clusterPalette[place.cluster % clusterPalette.length];
    }
    return potensiColor[place.potensi_pengembangan] || "#3b82f6";
  }

  function passesFilter(place){
    if (!state.kategori.has(place.kategori)) return false;
    if (!state.popularitas.has(place.prediksi_popularitas)) return false;
    if (!state.potensi.has(place.potensi_pengembangan)) return false;
    if (state.search && place.nama.toLowerCase().indexOf(state.search) === -1) return false;
    return true;
  }

  var pinIcon = L.divIcon({
    className: "",
    html: '<svg width="30" height="42" viewBox="0 0 34 46" xmlns="http://www.w3.org/2000/svg">'
      + '<path d="M17 0C7.6 0 0 7.6 0 17c0 12.7 17 29 17 29s17-16.3 17-29C34 7.6 26.4 0 17 0z" fill="#8e44ad"/>'
      + '<circle cx="17" cy="17" r="7" fill="#ffffff"/></svg>',
    iconSize: [30, 42],
    iconAnchor: [15, 42]
  });

  function renderMarkers(){
    markerLayer.clearLayers();
    if (currentMode === "heat") {
      if (heatLayer) { mapObj.removeLayer(heatLayer); heatLayer = null; }
      var pts = placesData.filter(passesFilter).map(function(p){
        return [p.lat, p.lon, Math.min(1, p.jumlah_rating / maxReview)];
      });
      heatLayer = L.heatLayer(pts, { radius: 25, blur: 20, maxZoom: 17 }).addTo(mapObj);
      return;
    } else if (heatLayer) {
      mapObj.removeLayer(heatLayer);
      heatLayer = null;
    }

    placesData.filter(passesFilter).forEach(function(place){
      var marker = L.circleMarker([place.lat, place.lon], {
        radius: radiusFromReview(place.jumlah_rating),
        fillColor: colorFor(place),
        color: "#ffffff",
        weight: 2,
        fillOpacity: 0.9
      });
      marker.on("click", function(){ selectPlace(place); });
      marker.addTo(markerLayer);
    });
  }

  function selectPlace(place){
    if (selectedPin) mapObj.removeLayer(selectedPin);
    selectedPin = L.marker([place.lat, place.lon], { icon: pinIcon, zIndexOffset: 1000 }).addTo(mapObj);
    mapObj.flyTo([place.lat, place.lon], Math.max(mapObj.getZoom(), 16), { duration: 0.6 });
    showInfoCard(place);
  }

  function showInfoCard(place){
    document.getElementById("ic-nama").textContent = place.nama;
    document.getElementById("ic-rating").textContent = place.rating.toFixed(1);
    document.getElementById("ic-review").textContent = "(" + place.jumlah_rating + " review)";

    var katEl = document.getElementById("ic-kategori");
    katEl.textContent = place.kategori;
    katEl.style.background = kategoriColor[place.kategori] || "#95a5a6";

    var popEl = document.getElementById("ic-popularitas");
    popEl.textContent = place.prediksi_popularitas.toUpperCase();
    var popColors = popBg[place.prediksi_popularitas] || ["#eee", "#333"];
    popEl.style.background = popColors[0];
    popEl.style.color = popColors[1];

    var potEl = document.getElementById("ic-potensi");
    potEl.textContent = place.potensi_pengembangan.toUpperCase();
    var potColors = potensiBg[place.potensi_pengembangan] || ["#eee", "#333"];
    potEl.style.background = potColors[0];
    potEl.style.color = potColors[1];

    document.getElementById("ic-cluster").textContent = "Cluster " + place.cluster;
    document.getElementById("ic-koordinat").textContent = place.lat.toFixed(7) + ", " + place.lon.toFixed(7);
    document.getElementById("ic-img").src = place.gambar_url;
    document.getElementById("ic-gmaps").href = "https://www.google.com/maps?q=" + place.lat + "," + place.lon;

    var full = Math.round(place.rating);
    var stars = "";
    for (var i = 0; i < 5; i++) stars += (i < full ? "\\u2605" : "\\u2606");
    document.getElementById("ic-stars").textContent = stars;

    document.getElementById("info-card").style.display = "block";
  }

  document.getElementById("info-card-close").addEventListener("click", function(){
    document.getElementById("info-card").style.display = "none";
    if (selectedPin) { mapObj.removeLayer(selectedPin); selectedPin = null; }
  });

  var searchInput = document.getElementById("search-input");
  var searchResults = document.getElementById("search-results");
  searchInput.addEventListener("input", function(){
    var q = this.value.trim().toLowerCase();
    state.search = q;
    if (q.length === 0) {
      searchResults.style.display = "none";
      renderMarkers();
      return;
    }
    var matches = placesData.filter(function(p){
      return p.nama.toLowerCase().indexOf(q) !== -1;
    }).slice(0, 6);
    searchResults.innerHTML = matches.map(function(p){
      return '<div class="search-item" data-nama="' + p.nama.replace(/"/g, "&quot;") + '">' + p.nama + "</div>";
    }).join("");
    searchResults.style.display = matches.length ? "block" : "none";
    renderMarkers();
  });
  searchResults.addEventListener("click", function(e){
    var el = e.target.closest(".search-item");
    if (!el) return;
    var nama = el.getAttribute("data-nama");
    var place = placesData.find(function(p){ return p.nama === nama; });
    if (place) selectPlace(place);
    searchResults.style.display = "none";
  });

  function setupFilterGroup(groupName, allValues, containerId, masterId){
    var container = document.getElementById(containerId);
    var master = document.getElementById(masterId);
    master.addEventListener("change", function(){
      var boxes = container.querySelectorAll('input[type="checkbox"]:not(#' + masterId + ")");
      boxes.forEach(function(b){ b.checked = master.checked; });
      state[groupName] = master.checked ? new Set(allValues) : new Set();
      renderMarkers();
    });
    container.querySelectorAll('input[type="checkbox"]:not(#' + masterId + ")").forEach(function(box){
      box.addEventListener("change", function(){
        if (box.checked) state[groupName].add(box.value);
        else state[groupName].delete(box.value);
        var boxes = Array.prototype.slice.call(
          container.querySelectorAll('input[type="checkbox"]:not(#' + masterId + ")")
        );
        master.checked = boxes.every(function(b){ return b.checked; });
        renderMarkers();
      });
    });
  }

  var kategoriListJS = Array.from(new Set(placesData.map(function(p){ return p.kategori; })));
  setupFilterGroup("kategori", kategoriListJS, "filter-kategori", "kategori-all");
  setupFilterGroup("popularitas", ["Sangat Populer", "Populer"], "filter-popularitas", "popularitas-all");
  setupFilterGroup("potensi", ["Sangat Potensial", "Potensial", "Dipertahankan", "Direkomendasikan Kunjungan"], "filter-potensi", "potensi-all");

  document.querySelectorAll('input[name="layer-mode"]').forEach(function(radio){
    radio.addEventListener("change", function(){
      currentMode = this.value;
      renderMarkers();
    });
  });

  document.getElementById("zoom-in").addEventListener("click", function(){ mapObj.zoomIn(); });
  document.getElementById("zoom-out").addEventListener("click", function(){ mapObj.zoomOut(); });
  document.getElementById("zoom-reset").addEventListener("click", function(){
    mapObj.setView([__CENTER_LAT__, __CENTER_LON__], 15);
  });

  renderMarkers();

  var kategoriCounts = __KATEGORI_COUNTS_JSON__;
  var pieCanvas = document.getElementById("pie-chart");
  if (pieCanvas && window.Chart) {
    new Chart(pieCanvas.getContext("2d"), {
      type: "pie",
      data: {
        labels: Object.keys(kategoriCounts),
        datasets: [{
          data: Object.values(kategoriCounts),
          backgroundColor: Object.keys(kategoriCounts).map(function(k){ return kategoriColor[k] || "#95a5a6"; })
        }]
      },
      options: { plugins: { legend: { display: false } }, responsive: true, maintainAspectRatio: false }
    });
  }
})();
"""

"""## Step 10 — Gabungkan Semua & Simpan sebagai File HTML"""

# ==========================================================
# STEP 10 - GABUNGKAN SEMUA & SIMPAN FILE HTML
# ==========================================================

final_html = (
    HTML_TEMPLATE
    .replace("__FOLIUM_HEAD__", folium_head)
    .replace("__FOLIUM_BODY__", folium_body)
    .replace("__FOLIUM_SCRIPT__", folium_script)
    .replace("__CUSTOM_JS__", CUSTOM_JS_TEMPLATE
             .replace("__DATA_JSON__", data_json)
             .replace("__MAP_VAR__", map_var_name)
             .replace("__CENTER_LAT__", str(center_lat))
             .replace("__CENTER_LON__", str(center_lon))
             .replace("__KATEGORI_COUNTS_JSON__", kategori_counts_json))
    .replace("__TOTAL_WISATA__", str(total_wisata))
    .replace("__RATA_RATING__", str(rata_rating))
    .replace("__TOTAL_REVIEW__", f"{total_review:,}".replace(",", "."))
    .replace("__UPDATE_TERAKHIR__", update_terakhir)
    .replace("__FILTER_KATEGORI_HTML__", build_filter_checkboxes(kategori_list, "kategori"))
    .replace("__FILTER_POTENSI_HTML__", build_filter_checkboxes(potensi_list, "potensi"))
    .replace("__PIE_LEGEND_HTML__", build_pie_legend(kategori_counts, total_wisata))
    .replace("__TOP5_RATING_HTML__", build_top5_rating(top5_rating))
    .replace("__TOP5_REVIEW_HTML__", build_top5_review(top5_review))
)
print("===== DEBUG =====")
print("map_var_name =", map_var_name)
print("folium_head =", len(folium_head))
print("folium_body =", len(folium_body))
print("folium_script =", len(folium_script))

print("folium_body preview:")
print(folium_body[:300])
OUTPUT_FILE = "dashboard_wisata_larantuka.html"
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(final_html)

print(f"Dashboard tersimpan sebagai: {OUTPUT_FILE}")

"""## Step 11 — Tampilkan Dashboard & Download"""

# ==========================================================
# STEP 11 - TAMPILKAN DI COLAB & DOWNLOAD
# ==========================================================

# Tampilkan langsung di dalam notebook
display(IFrame(src=OUTPUT_FILE, width="100%", height=900))

# Download file HTML ke komputer (khusus di Google Colab)
try:
    from google.colab import files
    files.download(OUTPUT_FILE)
except Exception as e:
    print("Bukan environment Google Colab, lewati proses download otomatis:", e)

